profile:
  umbra: 1
  reddwarf: 2
  redgiant: 3

dotfiles_path:
  scripts: plans/scripts/files

home_path:
  gobin: .local/bin
  gopath: .local/share/go
  repos: Repositories
  vendor: Repositories/vendor
  dotfiles: Repositories/dotfiles
  notes: Documents/notes
  bin: .local/bin
