profile:
  umbra: 1
  reddwarf: 2
  NEWHOST: 3

dotfiles_path:
  scripts: plans/scripts/files

home_path:
  npm: .npm-packages
  gobin: .local/bin
  gopath: .local/share/go
  repos: repos
  dotfiles: repos/dotfiles
  bin: bin
