[alias]
open = 'cd $ZK_NOTEBOOK_DIR; $EDITOR .'
o = 'zk open'
search = '$EDITOR "+:ZkNotes { sort = "modified" }"'
s = 'zk search'
i = 'zk index'
e = 'zk edit'
status = 'cd $ZK_NOTEBOOK_DIR; git status'
st = 'zk status'
diff = 'cd $ZK_NOTEBOOK_DIR; git add -N -A; git diff'
di = 'zk diff'
pull = 'cd $ZK_NOTEBOOK_DIR; git pull'
push = 'cd $ZK_NOTEBOOK_DIR; zk index; git add -A; git ci -m "$USER pushed latest notes from $HOSTNAME"; git push'
sync = 'zk pull; zk push'
conf = '$EDITOR "$ZK_NOTEBOOK_DIR/.zk/config.toml"'
