#
# Requires stack to be available
#
- name: Register KMonad repo
  stat:
    path: "/home/{{ target_user }}/{{ home_path.repos }}/kmonad"
  register: kmonad_repo

- name: Clone KMonad
  ansible.builtin.git:
    repo: https://github.com/kmonad/kmonad.git
    depth: 50
    dest: "/home/{{ target_user }}/{{ home_path.repos }}/kmonad"
  when:
    - not kmonad_repo.stat.exists
    - not "profile_1 == 'true'"

- name: Register kmonad executable
  stat:
    path: "/home/{{ target_user }}/.local/bin/kmonad"
  register: kmonad_executable

- name: Build KMonad
  shell: stack install
  args:
    chdir: "/home/{{ target_user }}/{{ home_path.repos }}/kmonad"
    creates: "/home/{{ target_user }}/.local/bin/kmonad"
  when:
    - not kmonad_executable.stat.exists
    - not "profile_1 == 'true'"

- name: Ensure group KMonad groups exists
  become: yes
  become_user: root
  group:
    name: "{{ item }}"
    state: present
  loop:
    - input
    - uinput
  when:
    - not "profile_1 == 'true'"

- name: Adding user {{ target_user }} to uinput group
  become: yes
  user:
    name: "{{ target_user }}"
    groups: input,uinput
    append: yes
  when:
    - not "profile_1 == 'true'"

- name: Create uinput rules file
  become: yes
  copy:
    dest: /etc/modules-load.d/uinput.conf
    content: uinput
  when:
    - not "profile_1 == 'true'"

- name: Create uinput rules file
  become: yes
  copy:
    dest: /etc/udev/rules.d/90-uinput.rules
    content: |
      KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"
  when:
    - not "profile_1 == 'true'"
