- name: Register .npm-packages directory
  stat:
    path: "/home/{{ target_user }}/{{ home_path.npm }}"
  register: npm_dir

- name: Tell npm where to store user packages
  shell: npm config set prefix "$HOME/{{ home_path.npm }}"
  when: not npm_dir.stat.exists

- name: Install general node packages
  community.general.npm:
    name: yarn
    global: yes
  loop:
  environment:
    NPM_PACKAGES: "/home/{{ target_user }}/{{ home_path.npm }}"
