- name: Run "dot build"
  shell: "/home/{{ target_user }}/{{ home_path.dotfiles }}/bin/dot build"

- name: Perform the following post-install steps
  debug:
    msg: |
      Reboot the system in order for all the changes to take place. After
      reboot, select "Awesome" as a window manager and run "dot postinstall",
      and follow the instructions.
