- name: Install emacs
  become: yes
  dnf:
    name:
    - emacs

- name: Register chemacs2 repo
  stat:
    path: "{{ ansible_env.HOME }}/.emacs.d"
  register: chemacs2_repo

- name: Install chemacs2
  ansible.builtin.git:
    repo: https://github.com/plexus/chemacs2.git
    depth: 50
    dest: "{{ ansible_env.HOME }}/.emacs.d"
  when:
    - not chemacs2_repo.stat.exists
