- name: Create .fonts directory
  file:
    name: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory

- name: Register iosevka fonts
  find:
    paths: "{{ ansible_env.HOME }}/.local/share/fonts"
    patterns: 'Iosevka*'
  register: iosevka_fonts

- name: Install Iosevka fonts
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/Iosevka.zip
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    remote_src: yes
  when: iosevka_fonts.matched == 0
