- name: Create .fonts directory
  file:
    name: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory

- name: Register Iosevka fonts
  find:
    paths: "{{ ansible_env.HOME }}/.local/share/fonts"
    patterns: 'Iosevka-*'
  register: iosevka_fonts

- name: Register IosevkaEtoile fonts
  find:
    paths: "{{ ansible_env.HOME }}/.local/share/fonts"
    patterns: 'IosevkaEtoile-*'
  register: iosevka_etoile_fonts

- name: Install Iosevka fonts
  ansible.builtin.unarchive:
    src: https://github.com/be5invis/Iosevka/releases/download/v30.1.1/PkgTTF-Iosevka-30.1.1.zip
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    remote_src: yes
  when: iosevka_fonts.matched == 0

- name: Install Iosevka fonts
  ansible.builtin.unarchive:
    src: https://github.com/be5invis/Iosevka/releases/download/v30.1.1/PkgTTF-IosevkaEtoile-30.1.1.zip
    dest: "{{ ansible_env.HOME }}/.local/share/fonts"
    remote_src: yes
  when: iosevka_etoile_fonts.matched == 0
