- name: Install neovim build dependencies
  become: yes
  dnf:
    name:
    - ninja-build
    - libtool
    - autoconf
    - automake
    - cmake
    - gcc
    - gcc-c++
    - make
    - pkgconfig
    - unzip
    - patch
    - gettext
    - curl
    - nodejs

- name: Register nvim binary
  stat:
    path: /usr/local/bin/nvim
  register: neovim_binary

- name: Register neovim repo
  stat:
    path: "/home/{{ target_user }}/{{ home_path.vendor }}/neovim"
  register: neovim_repo

- name: Clone neovim
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim
    depth: 50
    version: stable
    dest: "/home/{{ target_user }}/{{ home_path.vendor }}/neovim"
  when:
    - not neovim_repo.stat.exists
    - not neovim_binary.stat.exists

- name: Build neovim from source
  become: yes
  make:
    chdir: "/home/{{ target_user }}/{{ home_path.vendor }}/neovim"
    target: install
    params:
      CMAKE_BUILD_TYPE: Release
  when:
    - not neovim_binary.stat.exists

- name: Install npm dependencies for neovim
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop:
    - js-beautify
    - stylelint
    - marked
    - bash-language-server
    - vscode-langservers-extracted
    - sql-language-server
    - yaml-language-server
    - dockerfile-language-server-nodejs
    - diagnostic-languageserver
    - '@tailwindcss/language-server'
    - typescript-language-server
    - typescript

- name: Install denojs
  ansible.builtin.shell: curl -fsSL https://deno.land/x/install/install.sh | sh
  args:
    creates: "/home/{{ target_user }}/.deno/bin/deno"

- name: Create sumneko_lua folder
  file:
    name: "/home/{{ target_user }}/.local/bin/sumneko_lua"
    state: directory

- name: Install sumneko_lua
  ansible.builtin.unarchive:
    src: https://github.com/sumneko/lua-language-server/releases/download/2.5.6/lua-language-server-2.5.6-linux-x64.tar.gz
    dest: "/home/{{ target_user }}/.local/bin/sumneko_lua"
    remote_src: yes

- name: Install rust lsp dependencies
  become: yes
  dnf:
    name:
    - rust-analyzer
    - rust
    - cargo
