- name: Install rpmfusion repositories
  become: yes
  dnf:
    disable_gpg_check: yes
    name:
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"


- name: Install core packages
  become: yes
  dnf:
    name:
    - libtool
    - autoconf
    - automake
    - cmake
    - gcc
    - gcc-c++
    - make
    - pkgconfig
    - patch
    - gettext
    - wget
    - unzip
    - curl
    - clang
    - urlview
    - ncdu
    - tldr
    - ripgrep
    - fd-find
    - aspell
    - aspell-en
    - xdg-user-dirs
    - ImageMagick
    - renameutils
    - deluge
    - git
    - git-credential-libsecret
    - git-delta
    - gh
    - ruby
    - ruby-devel
    - jpegoptim
    - yt-dlp
    - youtube-dl
    - direnv
    - zig
    - texlive-scheme-full

# - name: Start docker daemon service
#   become: yes
#   ansible.builtin.systemd:
#     name: docker
#     enabled: yes
#     state: started

- name: Install valkey (redis) package
  become: yes
  dnf:
    name:
    - valkey

- name: Start database services
  become: yes
  ansible.builtin.systemd:
    name: valkey
    enabled: yes
    state: started

- name: Install NVidia drivers
  become: yes
  dnf:
    name:
    - akmod-nvidia
  when: "profile == '1'"
