- name: Install rpmfusion repositories
  become: yes
  dnf:
    disable_gpg_check: yes
    name:
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Add repo for Github command line utility
  become: yes
  yum_repository:
    name: gh-cli
    description: Github CLI
    baseurl: https://cli.github.com/packages/rpm/gh-cli.repo

- name: Update system
  become: yes
  dnf:
    name: '*'
    state: latest

- name: Install core packages
  become: yes
  dnf:
    name:
    - '@Multimedia'
    - '@base-x'
    - vim
    - firefox
    - wget
    - unzip
    - xclip
    - curl
    - clang
    - sensible-utils
    - xdotool
    - screenkey
    - redshift
    - urlview
    - xbacklight
    - xset
    - xprop
    - xsel
    - playerctl
    - ncdu
    - tldr
    - awesome
    - rofi
    - ripgrep
    - fd-find
    - aspell
    - aspell-en
    - feh
    - pulseaudio-utils
    - xinput
    - imwheel
    - xrandr
    - xdg-user-dirs
    - ImageMagick
    - renameutils
    - xss-lock
    - xsecurelock
    - acpi
    - bat
    - alacritty
    - easyeffects
    - pavucontrol
    - lxappearance
    # - greybird-dark-theme
    # - peek
    # - deluge
    # - seahorse
    - zathura
    - zathura-pdf-poppler
    - gimp
    - git
    - git-credential-libsecret
    - git-delta
    - gh
    - ruby
    - ruby-devel
    - nodejs

- name: Install NVidia drivers
  become: yes
  dnf:
    name:
    - akmod-nvidia
  when: "profile_1 == 'true'"

- name: Install zoom rpm
  become: yes
  dnf:
     name: https://zoom.us/client/latest/zoom_x86_64.rpm
     disable_gpg_check: yes
     state: present

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    method: user
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  community.general.flatpak:
    method: user
    name: "{{ item }}"
  loop:
    - com.microsoft.Teams
    - com.spotify.Client
    - com.skype.Client
    - org.telegram.desktop
    - com.discordapp.Discord
    - org.signal.Signal

- name: Install ruby gems
  shell: "/home/{{ target_user }}/{{ home_path.dotfiles }}/{{ dotfiles_path.scripts }}/sys-ensure-gems-installed"

- name: Register .npm-packages directory
  stat:
    path: "/home/{{ target_user }}/{{ home_path.npm }}"
  register: npm_dir

- name: Tell npm where to store user packages
  shell: npm config set prefix "$HOME/{{ home_path.npm }}"
  when: not npm_dir.stat.exists

- name: Install general node packages
  community.general.npm:
    name: yarn
    global: yes
  loop:
  environment:
    NPM_PACKAGES: "/home/{{ target_user }}/{{ home_path.npm }}"
