- name: Install rpmfusion repositories
  become: yes
  dnf:
    disable_gpg_check: yes
    name:
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Add repo for Github command line utility
  become: yes
  yum_repository:
    name: gh-cli
    description: Github CLI
    baseurl: https://cli.github.com/packages/rpm
    gpgkey: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x23F3D4EA75716059

- name: Update system
  become: yes
  dnf:
    name: '*'
    state: latest

- name: Install core packages
  become: yes
  dnf:
    name:
    - '@Multimedia'
    - '@base-x'
    - vim
    - firefox
    - thunderbird
    - wget
    - unzip
    - xclip
    - curl
    - clang
    - sensible-utils
    - xdotool
    - screenkey
    - redshift
    - urlview
    - xbacklight
    - xset
    - xprop
    - xsel
    - playerctl
    - ncdu
    - tldr
    - awesome
    - rofi
    - ripgrep
    - fd-find
    - aspell
    - aspell-en
    - pulseaudio-utils
    - xinput
    - imwheel
    - xrandr
    - xdg-user-dirs
    - ImageMagick
    - renameutils
    - xss-lock
    - xsecurelock
    - acpi
    - bat
    - alacritty
    - easyeffects
    - pavucontrol
    - flameshot
    - lxappearance
    - deluge
    - zathura
    - zathura-pdf-poppler
    - zathura-pdf-mupdf
    - gimp
    - git
    - git-credential-libsecret
    - git-delta
    - gh
    - ruby
    - ruby-devel
    - jpegoptim

- name: Install redis packages
  become: yes
  dnf:
    name:
    - redis

- name: Start database services
  become: yes
  ansible.builtin.systemd:
    name: redis
    enabled: yes
    state: started

- name: Install NVidia drivers
  become: yes
  dnf:
    name:
    - akmod-nvidia
  when: "profile == '1'"

# NOTE: skipped
- name: Install zoom rpm
  become: yes
  dnf:
     name: https://zoom.us/client/latest/zoom_x86_64.rpm
     disable_gpg_check: yes
     state: present
  when: "variant == 'all' and false"

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    method: user
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpaks
  community.general.flatpak:
    method: user
    name: "{{ item }}"
  loop:
    - com.spotify.Client
    - org.telegram.desktop
    - org.signal.Signal
    - com.slack.Slack

- name: Install ruby gems
  shell: "/home/{{ target_user }}/{{ home_path.dotfiles }}/{{ dotfiles_path.scripts }}/sys-gems-init"
