- name: Run "dot build"
  shell: "/home/{{ target_user }}/{{ home_path.dotfiles }}/bin/dot build"

- name: Install ruby gems
  shell: "/home/{{ target_user }}/bin/sys-ensure-gems-installed"

- name: Perform the following post-install steps
  debug:
    msg: |
      Reboot the system in order for all the changes to take place. After
      reboot, start X with 'startx', run 'dot postinstall', and follow the
      instructions.
