- name: Install redis packages
  become: yes
  dnf:
    name:
    - redis

- name: Start database services
  become: yes
  ansible.builtin.systemd:
    name: redis
    enabled: yes
    state: started
