- name: Install tmux
  become: yes
  dnf:
    name: tmux

- name: Register ~/.tmux
  find:
    paths: "/home/{{ target_user }}/.tmux/README.md"
  register: oh_my_tmux

- name: Install oh-my-tmux
  ansible.builtin.git:
    repo: https://github.com/gpakosz/.tmux.git
    depth: 50
    dest: "/home/{{ target_user }}/.tmux"
  when: oh_my_tmux.matched == 0

- name: Update oh-my-tmux
  shell: git pull
  args:
    chdir: "/home/{{ target_user }}/.tmux"
  when: oh_my_tmux.matched == 1

- name: Copy base config
  copy:
    src: "/home/{{ target_user }}/.tmux/.tmux.conf"
    dest: "/home/{{ target_user }}/.tmux.conf"
