- name: Install vifm and deps
  become: yes
  dnf:
    name:
    - gtk-devel
    - vifm

- name: Register dragon binary
  stat:
    path: "/home/{{ target_user }}/.local/bin/dragon"
  register: dragon_binary

- name: Register dragon repo
  stat:
    path: "/home/{{ target_user }}/{{ home_path.repos }}/dragon"
  register: dragon_repo

- name: Clone dragon
  ansible.builtin.git:
    repo: https://github.com/mwh/dragon
    depth: 50
    version: stable
    dest: "/home/{{ target_user }}/{{ home_path.repos }}/dragon"
  when:
    - not dragon_repo.stat.exists
    - not dragon_binary.stat.exists

- name: Build dragon from source
  make:
    chdir: "/home/{{ target_user }}/{{ home_path.repos }}/dragon"
    target: install
    params:
      CMAKE_BUILD_TYPE: Release
  when:
    - not dragon_binary.stat.exists
