- name: Install zk deps
  become: yes
  dnf:
    name:
    - go
    - libicu-devel

- name: Register zk repo
  stat:
    path: "/home/{{ target_user }}/{{ home_path.repos }}/zk"
  register: zk_repo

- name: Clone zk
  ansible.builtin.git:
    repo: https://github.com/mickael-menu/zk
    dest: "/home/{{ target_user }}/{{ home_path.repos }}/zk"
  when: not zk_repo.stat.exists

- name: Register zk executable
  stat:
    path: "/home/{{ target_user }}/.local/bin/zk"
  register: zk_executable

- name: Build zk
  shell: make install
  args:
    chdir: "/home/{{ target_user }}/{{ home_path.repos }}/zk"
    creates: "/home/{{ target_user }}/.local/bin/zk"
  when: not zk_executable.stat.exists
  environment:
    GOPATH: "/home/{{ target_user }}/{{ home_path.gopath }}"
    GOBIN: "/home/{{ target_user }}/{{ home_path.gobin }}"
