#!/usr/bin/env bash

if [ -n "$1" ] && [ -n "$2" ] && [ -n "$3" ]; then
  grep -rn "$1" "$3" | cut -f1 -d':' | xargs sed -i "s/$1/$2/"
else
  echo "Usage: $0 <text-to-replace> <text-replacement> <path>"
fi
