local tree = require('nvim-tree.config').nvim_tree_callback

vim.g.nvim_tree_bindings = {
  -- ["<CR>"] = ":YourVimFunction()<cr>",
  -- ["u"] = ":lua require'some_module'.some_function()<cr>",

  { key = {"<CR>", "o"},     cb = tree("edit") },
  -- { key = {"<2-LeftMouse>"}, cb = tree("edit") },
  -- { key = {"<2-RightMouse>"},= cb tree("cd") },
  { key = {"="},             cb = tree("cd") },
  { key = {"-"},             cb = tree("dir_up") },
  { key = {"<C-v>"},         cb = tree("vsplit") },
  { key = {"<C-s>"},         cb = tree("split") },
  { key = {"<C-t>"},         cb = tree("tabnew") },
  { key = {"K"},             cb = tree("prev_sibling") },
  { key = {"J"},             cb = tree("next_sibling") },
  { key = {"<BS>"},          cb = tree("close_node") },
  -- { key = {"<S-CR>"},        cb = tree("close_node") },
  { key = {"<Tab>"},         cb = tree("preview") },
  -- { key = {"<Tab>"},         cb = tree("preview") },
  { key = {"I"},             cb = tree("toggle_ignored") },
  { key = {"H"},             cb = tree("toggle_dotfiles") },
  { key = {"<C-r>"},         cb = tree("refresh") },
  { key = {"a"},             cb = tree("create") },
  { key = {"d"},             cb = tree("remove") },
  { key = {"r"},             cb = tree("rename") },
  { key = {"R"},             cb = tree("full_rename") },
  { key = {"c"},             cb = tree("cut") },
  { key = {"y"},             cb = tree("copy") },
  { key = {"p"},             cb = tree("paste") },
  { key = {"C-p"},           cb = tree("prev_git_item") },
  { key = {"C-n"},           cb = tree("next_git_item") },
  { key = {"q"},             cb = tree("close") },
}
