local tree = require('nvim-tree.config').nvim_tree_callback

vim.g.nvim_tree_bindings = {
  -- ["<CR>"] = ":YourVimFunction()<cr>",
  -- ["u"] = ":lua require'some_module'.some_function()<cr>",

  ["<CR>"]           = tree("edit"),
  ["o"]              = tree("edit"),
  -- ["<2-LeftMouse>"]  = tree("edit"),
  -- ["<2-RightMouse>"] = tree("cd"),
  ["="]              = tree("cd"),
  ["-"]              = tree("dir_up"),
  ["<C-v>"]          = tree("vsplit"),
  ["<C-s>"]          = tree("split"),
  ["<C-t>"]          = tree("tabnew"),
  ["K"]              = tree("prev_sibling"),
  ["J"]              = tree("next_sibling"),
  ["<BS>"]           = tree("close_node"),
  -- ["<S-CR>"]         = tree("close_node"),
  ["<Tab>"]          = tree("preview"),
  -- ["<Tab>"]          = tree("preview"),
  ["I"]              = tree("toggle_ignored"),
  ["H"]              = tree("toggle_dotfiles"),
  ["<C-r>"]          = tree("refresh"),
  ["a"]              = tree("create"),
  ["d"]              = tree("remove"),
  ["r"]              = tree("rename"),
  ["R"]              = tree("full_rename"),
  ["c"]              = tree("cut"),
  ["y"]              = tree("copy"),
  ["p"]              = tree("paste"),
  -- ["[c"]             = tree("prev_git_item"),
  -- ["]c"]             = tree("next_git_item"),
  ["q"]              = tree("close"),
}
