- name: Install virt-manager
  become: yes
  dnf:
    name: '@virtualization'

- name: Uncomment unix_sock_group = "libvirt" at /etc/libvirt/libvirtd.conf
  become: yes
  replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '#unix_sock_group = "libvirt"'
    replace: 'unix_sock_group = "libvirt"'

- name: Uncomment unix_sock_rw_perms = "0770" at /etc/libvirt/libvirtd.conf
  become: yes
  replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '#unix_sock_rw_perms = "0770"'
    replace: 'unix_sock_rw_perms = "0770"'

- name: Start libvirtd service
  become: yes
  ansible.builtin.systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: Adding user to libvirt group
  become: yes
  user:
    name: "{{ target_user }}"
    groups: libvirt
    append: yes
