- name: Install neovim build dependencies
  become: yes
  apt:
    name:
    - ninja-build
    - libtool
    - autoconf
    - automake
    - cmake
    - gcc
    - gcc-c++
    - make
    - pkgconfig
    - unzip
    - patch
    - gettext
    - curl
    - nodejs

- name: Include neovim
  include_tasks: tasks/shared/neovim.yml
