#!/usr/bin/env ruby

# https://stackoverflow.com/questions/2928584/how-to-grep-search-through-committed-code-in-the-git-history

require 'ostruct'
require 'optparse'

config = OpenStruct.new(pattern: nil, verbose: false)

parser = OptionParser.new do |opts|
  opts.banner = <<~BANNER
    Search through "git log" by grepping only changed lines
  BANNER

  opts.on('-gPATTERN', '--grep=PATTERN', 'Pattern') do |pattern|
    config.pattern = pattern
  end

  opts.on('-v', '--verbose', 'Verbose output') do
    config.silent = true
  end

  opts.on_tail('--help', 'Print help') do
    puts opts
    exit
  end
end

begin
  parser.parse!

  if config.pattern
    command = "git log -S#{config.pattern} -p #{ARGV.join(" ")}"
    puts "Running #{command}" if config.verbose
    system(command)
  else
    puts "No pattern provided"
    puts parser.help
    exit
  end
rescue Interrupt
  puts "Exiting\n"
end

