#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'tty-prompt'
end

class FailedToPush < StandardError; end
class FailedToCreatePullRequest < StandardError; end

prompt = TTY::Prompt.new

begin
  begin
    branch = `git branch --show-current`.chomp
    pushed = system("git push -u origin #{branch}") if prompt.yes?("Push to origin/#{branch}?")
    raise FailedToPush unless pushed
  rescue FailedToPush
    puts 'Failed to push.'
    retry
  end

  create_pr = prompt.yes?('Create pull request?')
  as_draft = prompt.yes?('As draft?') if create_pr

  begin
    pr_created = system("gh pr create #{'-d' if as_draft} --fill") if create_pr
    raise FailedToCreatePullRequest if !pr_created && create_pr
  rescue FailedToCreatePullRequest
    puts 'Failed creating pull request'
    retry
  end

  system('gh pr view --web') if pr_created && prompt.yes?('Open pull request in browser?')
rescue Interrupt
  puts
  exit 130
end
