#!/bin/bash

# Stolen and adjusted from
# https://github.com/vincentbernat/awesome-configuration/blob/master/bin/xss-lock

me="$(readlink -f "$0")"

case "$1" in
    start)
        source $HOME/bin/sys-config-x
        configure_suspend
        exec xss-lock --notifier="$me notify" --transfer-sleep-lock "$me" lock
        ;;
    dim|notify)
        echo "notify: start"
        systemctl --user kill -s STOP redshift.service
        trap "systemctl --user kill -s CONT redshift.service" EXIT
        trap 'echo notify: user activity; kill %% 2> /dev/null; exit 0' HUP  # user activity
        trap 'echo notify: locker started; kill %% 2> /dev/null; exit 0' TERM # locker started
        outputs=($(xrandr --current | sed -n 's/\([^ ]*\) connected .*/\1/p'))
        for out in ${outputs[@]}; do
            xrandr --output $out --brightness 0.4
        done
        sleep infinity &
        wait
        echo "notify: end"
        ;;
    lock)
        echo "lock: lock screen"
        # Something may have mendled with screensaver settings
        source $HOME/bin/sys-config-x
        configure_suspend
        # First, pause any music player
        playerctl -a pause
        # Then, lock screen
        xsecurelock
        echo "lock: unlock screen"
        ;;
esac
