#!/usr/bin/env ruby

require 'ostruct'
require 'optparse'
require 'securerandom'
require 'fileutils'
require 'pry'

SOCKET_PATH = File.join(Dir.home, '.cache', 'nvim', 'sockets')
FileUtils.mkdir_p(SOCKET_PATH)
OPT_LIST = '--list'.freeze
OPT_RUN = '--run'.freeze
WHITELISTED_OPTS = [OPT_LIST, OPT_RUN].freeze
NVIM_OPTS = (ARGV.to_a - WHITELISTED_OPTS).join(' ')

parser = OptionParser.new do |opts|
  opts.banner = 'Set alacritty theme'

  opts.on(OPT_LIST, 'List neovim server sockets') do
    puts Dir[File.join(SOCKET_PATH, '**/*.sock')].map { |path| File.basename(path) }
  end

  opts.on(OPT_RUN, 'Start neovim with server socket') do
    @socket = "#{SecureRandom.hex(4)}.sock"
    FileUtils.touch(File.join(SOCKET_PATH, @socket)) if @socket
    system("/usr/local/bin/nvim --listen #{@socket} ".concat(NVIM_OPTS))
  end

  opts.on_tail('--help', 'Print help') do
    puts opts
    exit
  end
end

begin
  puts parser.parse('--help') && exit(1) if ARGV.empty?
  parser.parse(*(ARGV.to_a & WHITELISTED_OPTS ))
ensure
  File.delete(File.join(SOCKET_PATH, @socket)) if @socket
end
