- name: Fedora workstation
  hosts: "{{ target_host }}"
  vars_files:
  - "../config.yml"
  remote_user: "{{ target_user }}"
  tasks:
    - include_tasks: tasks/packages.yml

    - name: Install virtmanager?
      include_tasks: tasks/virt.yml
      when: "profile == '1'"
