- name: Fedora workstation
  hosts: "{{ target_host }}"
  vars_files:
  - "../config.yml"
  remote_user: "{{ target_user }}"
  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/tmux.yml
    - include_tasks: tasks/zk.yml
    - include_tasks: tasks/neovim.yml
    - name: Install KMonad
      include_tasks: tasks/kmonad.yml
      when: "profile == '2' or profile == '3'"
    - include_tasks: tasks/fonts.yml
    - name: Install intel configurations
      include_tasks: tasks/intel.yml
      when: "profile == '2' or profile == '3'"
    - include_tasks: tasks/postgresql.yml
    - include_tasks: tasks/mysql.yml
    - include_tasks: tasks/elasticsearch.yml
    - include_tasks: tasks/redis.yml
    - include_tasks: tasks/virt.yml
    - include_tasks: tasks/postinstall.yml
    # - include_tasks: tasks/arduino.yml
