- name: Workstation
  hosts: "{{ target_host }}"
  vars_files:
  - "../config.yml"
  remote_user: "{{ target_user }}"
  tasks:
    - include_tasks: "tasks/{{ ansible_distribution }}/packages.yml"
    - include_tasks: "tasks/shared/tmux.yml"
    - include_tasks: "tasks/{{ ansible_distribution }}/zk.yml"
    - include_tasks: "tasks/{{ ansible_distribution }}/neovim.yml"
    - include_tasks: "tasks/{{ ansible_distribution }}/kmonad.yml"
    - include_tasks: "tasks/shared/fonts.yml"
    - name: Install intel configurations
      include_tasks: "tasks/{{ ansible_distribution }}/intel.yml"
      when: "profile_2 == 'true'"
    # TODO include it later
    #- include_tasks: "tasks/{{ ansible_distribution }}/postgresql.yml"
    - include_tasks: "tasks/{{ ansible_distribution }}/mysql.yml"
    - include_tasks: "tasks/shared/evm.yml"
    - include_tasks: "tasks/{{ ansible_distribution }}/redis.yml"
    # - include_tasks: "tasks/{{ ansible_distribution }}/virt.yml"
    # - include_tasks: "tasks/{{ ansible_distribution }}/arduino.yml"
    # - include_tasks: "tasks/{{ ansible_distribution }}/docker.yml"
    - include_tasks: "tasks/shared/postinstall.yml"
