- name: Ubuntu Dev Environment
  hosts: "{{ target_host }}"
  vars_files:
  - "../config.yml"
  remote_user: "{{ target_user }}"
  tasks:
    - include_tasks: tasks/packages.yml
#    - include_tasks: tasks/fonts.yml
#    - include_tasks: tasks/tmux.yml
#
#    - name: Install kmonad?
#      include_tasks: tasks/kmonad.yml
#      when: "profile == '2' or profile == '3'"
#
#    - name: Install intel configurations?
#      include_tasks: tasks/intel.yml
#      when: "profile == '2' or profile == '3'"
#
#    - name: Install virtmanager?
#      include_tasks: tasks/virt.yml
#      when: "profile == '1'"
#
#    - name: Install arduino?
#      include_tasks: tasks/arduino.yml
#      when: "variant == 'all'"
